// Compact tree types the LLM works with.
//
// Nodes are addressed by a stable, content-derived `id`:
//   root.id = "r"
//   node.id = first 8 hex chars of sha256(parent.id + "|" + san)
//
// The derivation is a pure function of the tree structure, so IDs
// survive parse → mutate → export → reparse without needing to be
// persisted in the PGN. Sibling insertions, deletions and variation
// promotions all leave every other node's ID unchanged — the failure
// mode of path-based addressing (later paths shifting when an earlier
// op inserts a sibling) simply cannot happen. See src/pgn/paths.ts
// for the id → path resolution used to power mutation calls.
//
// 32-bit width (8 hex chars) means birthday-collision probability
// is ~10^-4 even at 1000 nodes — the largest prep files we see are
// well under that. On the rare parse-time collision we throw a clear
// error rather than persisting anything ambiguous.

export type PrepArrow = { color: string; from: string; to: string };
export type PrepHighlight = { color: string; square: string };
export type PrepAnnotations = { arrows: PrepArrow[]; highlights: PrepHighlight[] };

// Persisted engine eval stored inside the PGN as
// `[%ceo-eval sf=+0.20/38 lc0=+0.35/24 nag=$14]` inside a comment.
// Chosen so that (a) it's a standard ChessBase-style escape sequence
// the frontend can strip/ignore just like [%cal]/[%csl]/[%clk], and
// (b) it's a persistent record so read_prep_file can hand the LLM
// every position's eval without a fresh cloud_analyse.
//
// `cp` is White-POV centipawns as an integer (+20 = +0.20 pawns).
// `mate` is White-POV plies to mate (+5 = White mates in 5).
// PVs are NOT stored — they'd bloat the PGN and are readily
// regenerated by cloud_analyse if the LLM wants them.
export type StoredEngineEval = {
  cp?: number;
  mate?: number;
  depth?: number;
};
export type StoredEval = {
  sf?: StoredEngineEval;
  lc0?: StoredEngineEval;
  nag?: string;
};

export type PrepNode = {
  id: string;                // "r" for root; 8-hex-char content hash otherwise
  san: string | null;        // null for root
  fen: string;
  ply: number;               // 0 for root; +1 per ply
  comment?: string;          // plain text with [%cal]/[%csl]/[%ceo-eval] STRIPPED — those live below
  nags?: string[];           // e.g. ["$1", "$14"]
  annotations?: PrepAnnotations;
  ceoEval?: StoredEval;      // persisted engine eval, filled by auto_evaluate / cloud_analyse
  children: PrepNode[];      // children[0] is the mainline continuation
};

export type PrepTags = Record<string, string>;

export type PrepFile = {
  tags: PrepTags;
  root: PrepNode;
};

// Path: array of child indices from root. Empty = root itself.
// PATH is INTERNAL — LLM never sees it. Kept for the mutation
// implementation, which resolves node_id → path once and then walks
// the tree the same way it always has.
export type Path = number[];

// Named colours as they appear in the parsed tree. The wire format uses
// single-letter codes (G, R, Y, C, B, O); the tree uses these longer
// names to match how the frontend represents them.
export const COLOR_NAMES = ["green", "red", "yellow", "light-blue", "dark-blue", "orange"] as const;
export type ColorName = typeof COLOR_NAMES[number];

const COLOR_CODE_TO_NAME: Record<string, ColorName> = {
  G: "green", R: "red", Y: "yellow", C: "light-blue", B: "dark-blue", O: "orange",
};
const COLOR_NAME_TO_CODE: Record<string, string> = Object.fromEntries(
  Object.entries(COLOR_CODE_TO_NAME).map(([code, name]) => [name, code]),
);

export function colorFromCode(code: string): ColorName {
  return COLOR_CODE_TO_NAME[code.toUpperCase()] ?? "green";
}
export function codeFromColor(color: string): string {
  return COLOR_NAME_TO_CODE[color] ?? "G";
}
